---
title: "Prepare_Metadata.RMD"
output: html_document
date: "2023-12-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

This only needs to be done once to collect the groupIDs and bone phenotypes from Roberto's files
```{r}


# import and merge CosmosID data


meta<-read.csv("~/Dropbox (Harvard University)/2_Projects_HMAC/Emory_RobertoPacifici/2023_May/Analysis/SourceData/meta.csv")

mice1<-read.csv("~/Dropbox (Harvard University)/2_Projects_HMAC/Emory_RobertoPacifici/2023_May/Analysis/SourceData/Fig2/Male_vs_female_baseline_STRAINS.csv")
mice2<-read.csv("~/Dropbox (Harvard University)/2_Projects_HMAC/Emory_RobertoPacifici/2023_May/Analysis/SourceData/Fig3/Strains GAHT 4 wks males only.csv")
mice3<-read.csv("~/Dropbox (Harvard University)/2_Projects_HMAC/Emory_RobertoPacifici/2023_May/Analysis/SourceData/Fig4/Strains GAHT 4 wks Females only.csv")

mice1<-mice1[9:29]
mice2<-mice2[9:38]
mice3<-mice3[9:29]

joined<-left_join(mice1, mice2)
joined<-left_join(joined, mice3)

# Clean up column names and IDs so they match
colnames(joined) <-gsub("^X", "", colnames(joined))
colnames(joined) <-gsub("\\.", "-", colnames(joined))
joined<-t(joined)
tax<-joined[1,]
joined<-joined[-1,]
colnames(joined) = tax
joined<-data.frame(joined)
joined <- joined %>% mutate_all(as.numeric)

meta<-meta %>% select(Name, mouseID, Time, Sex, trt, orch, Fem.BV.TV )

meta<-data.frame(meta)
rownames(meta) = meta$Name

write.csv(meta, "data/first_batch/metadata.csv")
write.csv(joined, "data/first_batch/cosmos_profile.csv")
```

```